In [1]:
import pandas as pd
import numpy as np
import pickle

In [6]:
f = open("/home/yujia/Project/2023-07-20-individual_MR/res/02_ITE_analysis/01_table/LDL/CAD/03_variable_importance/driv_continuousW_shap_model3.pkl", "rb")
aaa = pickle.load(f)
f.close()

In [10]:
f = open("/home/yujia/Project/2023-07-20-individual_MR/res/02_ITE_analysis/01_table/TC/CAD/03_variable_importance/driv_binaryW_continuousZ_shap_model3.pkl", "rb")
bbb = pickle.load(f)
f.close()

In [11]:
bbb

defaultdict(dict,
            {'CAD': {'30690-0.0_1': .values =
              array([[-8.21682042e-06,  6.14987260e-05,  5.32670897e-04, ...,
                       0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
                     [ 9.79571519e-06, -8.24689088e-04, -1.49619924e-04, ...,
                       0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
                     [-7.02463723e-06,  1.31494353e-04, -1.46136851e-04, ...,
                       0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
                     ...,
                     [ 3.47129909e-06, -1.02878902e-04,  1.51722101e-04, ...,
                       0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
                     [-1.42498564e-05,  3.26647011e-05, -2.62892521e-04, ...,
                       0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
                     [-2.60392591e-06, -3.86350531e-04, -6.02615781e-04, ...,
                       0.00000000e+00,  0.00000000e+00,  0.00000000e+00]

In [5]:
aaa['CAD']['30690-0.0'].values

array([[-8.18201633e-08,  3.85247086e-07, -4.03054803e-06, ...,
         1.41696170e-06,  0.00000000e+00,  0.00000000e+00],
       [ 1.06911967e-07,  8.70490867e-06,  2.74708638e-06, ...,
         1.27265790e-06,  0.00000000e+00,  0.00000000e+00],
       [-1.40628155e-07, -1.17747597e-06, -2.33378162e-06, ...,
         1.39419309e-06,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 9.02680997e-08,  1.20441232e-06,  2.56711768e-07, ...,
         1.33297020e-06,  0.00000000e+00,  0.00000000e+00],
       [ 5.58008293e-08,  1.52273302e-06,  4.80584907e-06, ...,
         1.16438026e-06,  0.00000000e+00,  0.00000000e+00],
       [ 4.78471735e-08,  7.80224676e-06,  4.32342399e-06, ...,
         1.27562165e-06,  0.00000000e+00,  0.00000000e+00]])

In [7]:
aaa

defaultdict(dict,
            {'CAD': {'30780-0.0': .values =
              array([[ 1.23891994e-08, -2.93615557e-06, -1.84152518e-05, ...,
                       1.83273716e-06,  0.00000000e+00,  0.00000000e+00],
                     [-3.98926237e-07,  2.05115192e-05,  5.34743435e-06, ...,
                       1.45548526e-06,  0.00000000e+00,  0.00000000e+00],
                     [ 3.93142520e-07,  8.85227861e-07, -2.63257979e-06, ...,
                       1.26644885e-06,  0.00000000e+00,  0.00000000e+00],
                     ...,
                     [-1.25209589e-07, -1.29086567e-06, -3.09666344e-06, ...,
                       1.14759409e-06,  0.00000000e+00,  0.00000000e+00],
                     [ 4.62591440e-08, -5.77165924e-07,  5.96728891e-06, ...,
                       7.66608775e-07,  0.00000000e+00,  0.00000000e+00],
                     [ 3.32486321e-07, -2.09761305e-06,  5.77160356e-06, ...,
                       1.72371958e-06,  0.00000000e+00,  0.00000000e+00]])